Full project
Fezwer/dz_ymap pull request #1
Opened 2024-01-28 06:30 UTC by Fezwer

2024-01-29 09:24 UTC, Hostridet requested changes
Честно говоря, слабо, все накидано друг на друга, никакой структуру/архитектуры
Читаемость кода на нуле

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/widgets/map_page.dart
> +abstract class MapPage extends StatelessWidget {
зачем этот класс нужен?
Наследовать, чтобы тайтл зашить?

2024-01-29 09:24 UTC, Hostridet commented on lib/main.dart
> +  Future<void> _getCurrentLocation() async {
Получение и обработка данных не относится к логике экрана.
Вынести в репозиторий

2024-01-29 09:24 UTC, Hostridet commented on lib/main.dart
> +    permission = await Geolocator.checkPermission();
Запрос на нативную часть, может прилететь критика в теории (андроид любит менять пермишины в каждой версии)
Обернуть в `try catch`

2024-01-29 09:24 UTC, Hostridet commented on lib/main.dart
> +      permission = await Geolocator.requestPermission();
Аналогично

2024-01-29 09:24 UTC, Hostridet commented on lib/main.dart
> +    print('Нажатие по карте: $point');
Пользователь не умеет читать консоль, выведи на экран Snackbar

2024-01-29 09:24 UTC, Hostridet commented on lib/main.dart
> +              final mapObject = PlacemarkMapObject(
Мапим подставляя поля?
Мы уже 2024 году, реализуем у модели PlacemarkMapObject конструктор
`factory PlacemarkMapObject.fromObject(...) => PlacemarkMapObject(...)`

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/user_layer_page.dart
> +  Future<bool> get locationPermissionNotGranted async => !(await Permission.location.request().isGranted);
Этого здесь быть не должно, вынести в отдельную сущность

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/user_layer_page.dart
> +            key: mapKey,
В чем идея использования глобального ключа?
Тебе для чего-то нужен элемент/стейт?
(ответь комментарием)

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/user_layer_page.dart
> +                        print(await controller.getUserCameraPosition());
зачем что-то в консоль писать? Убрать

2024-01-29 09:24 UTC, Hostridet commented on lib/main.dart
> +      print(e);
Как пользователь поймет, что вылетело исключение?

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/suggest_page.dart
> +    await widget.session.reset();
Метод попадает в event queue и ждет, когда будет выполнена асинхронная операция
В этом время можно еще всяких кнопочек понажимать, тогда поймаем критику (в худшеим случае если вызовем _close() и _reset() практически одновременно)
Когда выполняется await нужно блокировать UI, обычно это делают с помощью `FutureBuilder`

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/suggest_page.dart
> +  Future<void> _suggest() async {
Не логика экрана. Вынести

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/suggest_page.dart
> +class SuggestionsPage extends MapPage {
Создавать `MapPage` чтобы зашить `title`? - gigachad
Усложнять читаемость кода, когда у тебя на самом деле константный тайтл...

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/search_page.dart
> +  Future<void> _cancel() async {
Повторение кода (DRY), может стоит вынести эту логику в отдельную сущность?

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/search_page.dart
> +  void _search() async {
Тут быть не должно

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/search_page.dart
> +    super.dispose();
dispose() в конце

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/reverse_search_page.dart
> +  Future<void> _cancel() async {
Снова повторение кода

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/reverse_search_page.dart
> +  final Future<SearchSessionResult> result;
На каждом экране передаешь данные, которые могут быть еще не получены или вообще не придти. 
Дождаться на прошлом экране, когда данные будут получены и передавать `SearchSessionResult`

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/polyline_map_object_page.dart
> +                          polyline: const Polyline(points: [
Вынести в модель`Polyline` `factory Polyline.poistions() return Polyline(...)` все равно константные значения, зачем захламлять экран?

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/polyline_map_object_page.dart
> +                          onTap: (PolylineMapObject self, Point point) => print('Tapped me at $point'),
Когда-нибудь пользователь научится читать консоль, но не сегодня

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/polyline_map_object_page.dart
> +                        final mapObject = mapObjects.firstWhere((el) => el.mapId == mapObjectId) as PolylineMapObject;
`.firstWhere` над списком, где mapObjects = [] по умолчанию, если данных не будет, то будем смотреть на красный(дебаг)/белый(релиз) экран

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/driving_page.dart
> +  Future<void> _cancel() async {
Повторяемся, каждый экран дежавю

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/driving_page.dart
> +  final PlacemarkMapObject startPlacemark = PlacemarkMapObject(
Я понимаю, что скорее всего `PlacemarkMapObject` - это модель из пакета.
У тебя же ситуация, что из-за отсутствия необходимого конструткора приходится повторять код из раз в раз, может стоит создать свою модель с полями и конструкторами `fromMapObject`, `toMapObject`

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/clusterized_placemark_collection_page.dart
> +                            PlacemarkMapObject(
Уже писал про это

2024-01-29 09:24 UTC, Hostridet commented on lib/examples/bicycle_page.dart
> +    await Navigator.push(
Зачем тут await? Тебе не нужно ждать закрытие следующего экрана
unawaited()

2024-01-29 09:25 UTC, Hostridet commented on lib/main.dart
> +              final mapObject = PlacemarkMapObject(
Понимаю, что это модель из пакета, но это не оправдание, ниже расписал что и почему

2024-02-01 09:58 UTC, Fezwer commented on lib/main.dart
> +  Future<void> _getCurrentLocation() async {
zoomlevel нужен для экрана. Без него будут резкие скачки при приближении и отдалении

2024-02-01 11:44 UTC, Fezwer commented on lib/main.dart
> +  Future<void> _getCurrentLocation() async {
Не совсем понял. Вы хотите чтобы я их в другой файл перенес?

2024-08-02 15:54 UTC, merged